version: "3"
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: PiHole
    image: pihole/pihole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: "Europe/Sofia"
    volumes:
      - "${HOME}/pihole/etc-pihole/:/etc/pihole/"
      - "${HOME}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"

  # https://github.com/OctoPrint/octoprint-docker
  octoprint:
    container_name: OctoPrint
    image: octoprint/octoprint:latest
    restart: always
    environment:
      ENABLE_MJPG_STREAMER: "true"
      MJPG_STREAMER_INPUT: "-n -r 1920x1080 -f 30"
    ports:
      - "80:80"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/video0:/dev/video0"
    volumes:
      - "${HOME}/octoprint/:/octoprint/"
